MC/CustomGenerators/PWGLF/EPOS_StrInj_pPb8.C

Code to define a Custom Generator which implements a Cocktail with:
* EPOSLHC underlying event
* 3 Xi (or anti-Xi) pt-flat injected per event at high pt (2-20 GeV/c)
* 3 anti-Omega (Omega) pt-flat injected per event for all pt (0-10 GeV/c)
The generator is useful to complement with dedicated production the statistics of cascades contained in general purpose production.

Custom generator for pPb 8 TeV EPOSLHC MC generation with strangeness injection

---

AOD/AODtrainsim.C
MC/CheckESD.C
MC/ExportGRPinfo.C
MC/ReconstructionConfig.C
MC/SimulationConfig.C
MC/dpgsim.sh
QA/QAtrainsim.C

Along with `--ocdb [alien|local]` the `cvmfs[:/full/path]` is now supported. The
full path is optional and defaults to `/cvmfs/alice-ocdb.cern.ch`.
AliRoot version must be compatible with it.

Add CVMFS OCDB support in simulation

---

AOD/AODtrainsim.C
MC/Config.C
MC/GeneratorConfig.C
MC/ReconstructionConfig.C
MC/SimulationConfig.C
MC/dpgsim.sh
QA/QAtrainsim.C

Hi,
I added a new settings to run muon-only MC, like the ones we use for tracking systematics studies and for J/Psi, Upsilon, etc... AccEff correction calculations. This settings is different from the "muon" settings that correspond to the muon_calo passes and can be used for e.g. tracklet multiplicity studies or by UPC for STARLIGHT MC.
I tested successfully this new settings locally with single muon MC.
Also I tried to be careful not to change any existing behaviour with those modifications, but a double check is more than welcome! :-)
Cheers,
Philippe

new settings for muon only MC

---

MC/CustomGenerators/PWGGA/SingleParticleGun001.C

pT selections low/mid/high are added in order to generate particle in different pT region.
This will reduce CPU time from EM showers point of view in simulation.

add pT selection in single simulation for PHOS

---

MC/dpgsim.sh

This only happens if VDT is not already in `LD_PRELOAD`.
Adds also monitoring of VDT externally added to `LD_PRELOAD`.

Allow to enable VDT math library from dpgsim via --vdt

---

DataProc/CPass0/makeOCDB.C
DataProc/CPass1/makeOCDB.C

Dear all,
since we are very close to the limit of 100 bad chambers and that the QA did not point to any overmasking of the TRD chambers, I propose to increase slightly the validation limit for the TRD cpass0/cpass1.
Best regards,
Raphaelle

Increase the TRD validation limit by 10 chambers

---

MC/EXTRA/gen_ampt.sh
MC/GeneratorConfig.C

This pull request makes the stand-alone implementation of AMPT available in the AliDPG package
-  AMPT_v2267t is the latest version of AMPT, tuned to LHC run 2 energies (5.02 TeV CM energies)
-  the compiled binary ampt is available in VO_ALICE@AMPT::v1.26t7-v2.26t7-2. this package also contains a parser that parses the native ampt output to HepMC format (the executable is simple called 'parser')  for further processing in AliROOT
- This pull request calls AMPT by resolving the relevant packages via CVMFS and running AMPT as an independent process using the AliGenExtExec interface
Caveats
- This implementation is 'minimal': it serves the goal of showing that components for running are in place as @miweberSMI and I discussed today
- the configuration of the generator is hard-coded in the …

-- AMPT::v1.26t7-v2.26t7-2 --

---

DataProc/CPass0/makeOCDB.C
DataProc/CPass1/makeOCDB.C

Due to a LV server crashed, we expect 10 more chambers without data during the next two weeks. We need then to increase further the validation limit of TRD bad chambers. The limit will be put back after this period.

Further increase the validation limit of TRD bad chambers

---

MC/SimulationConfig.C

* Enabling TPC Hits->SDigits->Digits
* current default for TPC is Hits->Digits
* adding void to the function invocation (Optional?)
* correct C
* otherwise my editor was highlighting large faction of code as syntax error

ALIROOT-7077: ADD setup for the TPC ion tail and crosstalk simulation

---

QA/QAtrainsim.C

Hi Francesco,
As we discussed, I decoupled the MuonOnly and MuonCalo config.
For the MuonCalo, I explicitly disabled the tasks that I think cannot run with this reconstruction configuration (MUON ITS VZERO T0 AD), while letting the others as defined by default, assuming that if the default change it is also fine for MuonCalo.
I ran 2 tests locally to check:
i) that the config MuonOnly is unchanged
ii) that the config MuonCalo is OK, as far as I can tell... i.e. OK for muon tasks and it does not crash
Since I am not familiar with all the tasks in the train, can you please cross-check the MuonCalo config before merging?
Thanks and cheers,
Philippe

update Muon configuration

---

MC/CustomGenerators/DPG/PerformanceGenerator.C

* Performance generator to be used for fast MC pre-production validation
* Make performance generator with flat 1/pt and flat pdg () input jets
* Jet multiplicity smeared (Poisson) with mean value nJets
* nJets  defaults 1 (pp), 2(pPb), 10 (PbPb)
* can be overwritten by env variable PerformanceGenerator_nJets
* Before pull request  PerformaceGenerator.C was tested for pp and PbPb pre-production for ALIROT-7070 (GSI)
* see discussion in https://alice.its.cern.ch/jira/browse/ALIROOT-7077?focusedCommentId=206353&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-206353

 ATO-245: ADD  PerformanceGenerator.C(AliGenPerformance.cxx)

---

MC/CustomGenerators/PWGHF/Hijing_pPb_Lc.C
MC/CustomGenerators/PWGHF/Pythia6_Perugia2011_Lc.C

Patch to generation macros to fix issues brought up in 10% QA for LHC17j4(a,b,c,d) (cf https://alice.its.cern.ch/jira/browse/ALIROOT-7487?focusedCommentId=207352&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-207352)

fixes for multiplicity & trigger after 10% QA

---

MC/OCDBConfig.C
MC/dpgsim.sh

Added an optional argument to dpgsim, --OCDBTimeStamp which should be in the form <year>_<month>_<day>_<hour>_<minutes>_<seconds> and parsed in the OCDBConfig.C

OCDB time machine functionality

---

MC/CustomGenerators/PWGLF/Pythia8_Monash2013_RsnNcl001.C

This PR adapts the RsnNcl generator to the new AliGenCocktail mode that allows the user to use a single generator on top of a background event choosing randomly from the list of the generators. This new mode, as well as this generator, will be working with AliRoot master as soon as [this pr](https://github.com/alisw/AliRoot/pull/512) will be merged.
Cheers,
Max

Using new AliGenCocktail mode for RsnNcl production

---

MC/dpgsim.sh

Substituted --removeTrackRefs option by --keepTrackRefsFraction <percentage>
which enforces removal of TrackRefs.root in all but <percentage> fraction of jobs
Decision is taken randomly according to ALIEN_JDL_LPMJobID to be set by the sub-job JDL.
In absence of externally provided ALIEN_JDL_LPMJobID a warning will be printed
and locally generated random number will be assigned.
Default value of TrackRefs to keep is set in the declaration
CONFIG_KEEPTRACKREFSFRACTION=100, can be changed to any value between 0 and 100.
This patch should be accompanied by wildcarding e.g. as TrackRefs*.root saving request
in the JDL

added option to remove TR fraction

---

MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn002.C

Hi @miweberSMI @catalinristea ,
this fixes the issue discovered on the grid for the resonance generator.
In my local tests it is working, but it was the case also for the previous one... This time I checked also on lxplus and it should be OK. Please have a look!
Cheers,
Max

Fix string size in struct for the resonance generator

---

MC/CustomGenerators/PWGCF/Therminator2_001.C
MC/EXTRA/gen_therm2.sh
MC/GeneratorConfig.C

I've modified the generation script to handle full xml file paths.
The Therminator2 AliGenerator macro is now taking a path parameter for more flexibility. The given path is then expanded using `AliDataFile::GetFileName()` which allows for relative paths, such as `"PWGCF/file.xml"`.

Therminator2: preparing script and macro to handle new path formats

---

MC/EXTRA/gen_ampt.sh

Hi @miweberSMI ,
We have a new (nightly) build of AliGenerators, so we can now use AMPT with the HIJING patch from there. This PR configures AMPT for AliDPG such that it will use this new tag of AliGenerators . For testing it, I think we need a new tag of AliDPG. 
The new build of AliGenerators also contains the updated version of Therminator2, so if we request a new tag of AliDPG, it's better to wait also for the updated AliDPG scripts for Therminator2 and fix the two problems in one go. Currently I cannot make a PR for this, as it would conflict with #111 . If you merge #111 , I can open a new PR for Therminator2. Otherwise I would ask @maciekniewielki  to amend #111 .
Thanks,
Redmer

 load AMPT from nightly builds

---

MC/Config.C
MC/DetectorConfig.C
MC/Geant4Config.C
MC/SimulationConfig.C

Some small stuff (missing forward declaration, incorrect forward declaration). In Config.C consequently the ROOT5 code was executed under ROOT6 and vice versa. In case of doubts that the ROOT_VERISON_CODE macro works under ROOT5 in interpreted mode (what one can deduce from the comments) I recomment to use the "__CLING__" macro -  this has been verified that it properly separates the ROOT5 and ROOT6 case also in interpreted mode.

Fixes for ROOT6

---

MC/CustomGenerators/PWGLF/Hijing_XeXe_Nuclei.C

We wanted to inject 3He, not 3H, but I assumed the AliRoot ordering for nuclear states whereas in `Generator_Nuclex` 3He and 3H are swapped.

Inject 3He instead of 3H

---

MC/Config.C
MC/CreateSnapshot.C
MC/GeneratorConfig.C
MC/ReconstructionConfig.C
MC/rec.C
MC/sim.C

This PR combines a couple of fixes I had to apply to run AliDPG simulation with Root 6.
I am not 100% sure about the include paths. For me, it worked to remove the "MC/" before the files, but I think one could alternatively set a ROOT_INCLUDE_PATH to the AliDPG root, no idea what is better.

Fixes for running AliDPG MC with Root 6

---

QA/main_QAtrainsim.C

Should be double-checked by someone familiar with the QA
- This disables one task for EMCAL hard. However, the loading of the corresponding macro is commented out as well, so this cannot run in any case.
- This disables a special case for PHOS, which cannot compile by definition.

Fixes for running MC QA with ROOT6

---

MC/EXTRA/gen_therm2.sh

The fixed version of the Therminator2 generator has been released (see [here](https://alice.its.cern.ch/jira/browse/ALIROOT-7952)). I'm updating the generator script to include this change.

Updating Therminator2 version in the generator script

---

MC/GeneratorConfig.C

This include is needed when running the macro in ROOT 6, thanks to @chiarazampolli for pointing to the missing header.

Fix missing include for kPythia6HFYellowReport

---

QA/QAtrain_duo.C
QA/QAtrainsim.C
QA/main_QAtrain_duo.C
QA/main_QAtrainsim.C

Task `AliAnalysisTaskCaloCellsQA` exists with two different signatures. We need
to know which one we are using. Note that checking the AliRoot version is weak
(since we may not have a variable holding the version, for instance during
development). We now:
* check the macro file for the presence of the old signature,
* define a preprocessor directive accordingly (via `gInterpreter`).
The directive is processed before we invoke the corresponding
`main_QAtrain_duo.C` macro, and expanded properly there, in both ROOT 5 and 6.
Note that the old strategies are wrong/faulty for different reasons:
* conditionally checking the value of a boolean _at runtime_ does not prevent
ROOT 6 from still processing the lines it won't actually execute, leading to
errors for the incorrect signatures,
* loading …

Fix NULL vs. "" handling in PHOS CaloCells macros

---

Utils/CompareAllHistos.C
Utils/runCompareAllHistos.sh

We also allow CompareAllHistos.C to read files from any source instead of just
supporting local files by using `TFile::Open()` instead of `new TFile()`
@chiarazampolli @fprino

Add script to run CompareAllHistos.C

---

QA/QAtrainsim.C

this does not fail for some reason but just produces a warning, anyway it should be fixed.

Fix interpreter warning

---

MC/CustomGenerators/PWGDQ/Muon_GenParam.C

Hi @miweberSMI ,
I used a symbolic link as suggested (with a generic name, which is easier to handle in the generic macro). I tested and it works for me.
Cheers,
Philippe

add missing include path + compile parameterization macro locally

---

MC/dpgsim.sh

We need to converge on how to set the PID response in the macro.
Since currently the output of this macro is not looked at and not
even saved, it is ok to not run it.
See also discussion in https://github.com/alisw/AliDPG/commit/52bc50b3b690e4265406d8518a91e6adcccb5067#diff-110caea4b0dcf9bdb2a94892627e82f9

Don't run the CheckESD for now.

---

AOD/main_AODtrainRawAndMC.C
DataProc/CPass0/main_recCPass0.C
DataProc/CPass0/main_runCalibTrain.C
DataProc/CPass0/recCPass0.C
DataProc/CPass1/main_recCPass1.C
DataProc/CPass1/main_recCPass1_OuterDet.C
DataProc/CPass1/recCPass1.C
DataProc/Common/ConfigCalibTrain.C
DataProc/Common/main_runFilteringTask.C
DataProc/Common/raw2clust.C
DataProc/PPass/main_rec.C
DataProc/muon_calo/main_rec.C
QA/main_QAtrain_duo.C

This is to avoid unnecessary queries to alien, which often delay the jobs

Impose local OCDB DefaultStorage when snapshot is used

---

DataProc/CPass0/main_makeOCDB.C

Due to different definition of triggers for CPass0 and CPass1 in PbPb with respect to pp, the MeanVertex OCDB has to be created in CPass1

do not update MeanVertex in CPass0 in PbPb (LHC15o and LHC18q)

---

DataProc/CPass0/main_makeOCDB.C

Hello @afestant , 
I ping you only as I don't know Davide's git account... (If you do, please add him). 
I implemented the check also for 18r, now, for MeanVertex to not be done in CPass0 for this period. 
Cheers,
Chiara

Do not update MeanVertex in CPass0 also for 18r

---

DataProc/PPass/main_rec.C

@catalinristea : This is the main_rec.C to be used for the PPass, it uses ESD Clean by default.
To switch it off, use LPMESDCLEANOFF=1 in the JDL (not for this PbPb)

Switch ESD Clean ON by default

---

DataProc/skimming/JDL.jdl
DataProc/skimming/aliroot_dpgSkim.sh
DataProc/skimming/includeMacro.C
DataProc/skimming/runskim.sh
DataProc/skimming/skimRaw.C

I am adding the directory skimming with the code for the CALOFAST cluster raw data skimming from Martin. The code was modified to ensure that the minimum amount of data is read from the raw files.
The execution is triggered by by the aliroot_dpgSkim.sh which simply runs the ``$ALIDPG_ROOT/DataProcskimming/runskim.sh`` w/o any arguments. This latter is execting to have in the current directory the ``wn.xml`` file with URLs of raw data chunks to chain and skim. The output is stored in the file ``skim000<runNumber>.root`` (the runNumber is extracted automatically from the raw data). I am adding also the a sample JDL.jdl we were using before: @catalinristea , I am not familiar to the LPM machinery but obviously the real JDL will be different, adding this one just to indicate that 
1) we were …

added code for CALOFAST skimming

---

MC/CustomGenerators/PWGDQ/Muon_GenParamSingle_PbPb5TeV_1.C

Update of the single muons parametrisation for PbPb at 5 TeV from tunning on LHC18r data

New single muons parametrisation for PbPb 5TeV (LHC18r)

---

MC/DetectorConfig.C

Update DetectorInit(...) to automatically disable ADA PMT shielding if the year is less than 2017 as this is the year when the shielding was installed.

auto-disable ADA PMT shielding if year<2017

---

MC/CustomGenerators/PWGHF/Hijing_PbPb_Lc.C
MC/CustomGenerators/PWGHF/Hijing_pPb_Lc.C

Modify existing custom generator for Lc in pPb for signal training in ML studies to include option for forced decay chain of kaon from Lc (see https://github.com/alisw/AliRoot/pull/893). Also added new generator for PbPb that includes same.

Modifications to D2H custom generators for Lc

---

MC/DetectorConfig.C

Decide whether to create or not ADA PMT shielding based on the year passed to the title of the ADv1 constructor.
If year<=0, then do not pass that into the title, in which case AD will be constructed with default values (by default AD assumes that it must construct the shielding).

Decide if create ADA PMT shielding based on year

---

QA/main_QAtrain_duo.C

In AliPhysics v5-09-44b and from v5-09-46, the returned object of
the macro changed. Since we don't use it, we just remove it, to
remain backward compatible without checks on the version of AliPhysics.

Fix after changes in return value of the AddTaskEmcalTriggerQA_QAtrain.C

---

MC/GeneratorConfig.C
MC/dpgsim.sh

- as discussed on https://github.com/alisw/AliDPG/pull/241
- to make clear that not only v226t7 will be done like that but all versions onwards

Adapt naming of AMPT generator v2:

---

MC/CustomGenerators/PWGHF/Hijing_HF001.C
MC/CustomGenerators/PWGHF/Pythia6_Perugia2011_Lc.C

Changes trigger range for Lc from 1.6 to 1.0 in PbPb generator macro for dedicated Lc productions, as discussed in PB slides. (see https://alice.its.cern.ch/jira/browse/ALIROOT-8208) 
Also adds "forced" K0 decay channel to Pythia generator for Lc in pp.

trigger range 1.6 -> 1.0 in dedicated Lc PbPb generator macro

---

DataProc/TPCSPCalibration/morphMaps.C

Allows to merge with certain weight function 2 correction/distortions parameterizations, e.g. with different voxel binning.
To be used to create map with fine Z/X in the C-side low-R padrows keeping everywhere else 5-z-bins params, see ATO-463
Thus macro requires https://github.com/alisw/AliRoot/pull/917

Macro to morph 2 TPC SCD params together

---

MC/SimulationConfig.C

This needs current AliRoot master, i.e. commits b52ecaa4477312144a9611dffb47057ebc659e77 and b52ecaa4477312144a9611dffb47057ebc659e77.
It changes the HLT behavior such by default only the TPC compression runs, which should speed up MC simulation. We should double-check that this has no side effects.

Use HLT TPC-compression-only mode by default

---

MC/CustomGenerators/PWGLF/Pythia8_StrInj_pp5_2017.C

New custom generator for flat-pt injected lambda, Xi and Omega into Pythia8 Monash 2013.
Will be used for pp5TeV 2017 anchored MC production to increase stats for strange baryons

Pythia8 + inj strangeness for pp 5TeV 2017

---

MC/CustomGenerators/PWGDQ/GenJPsiParaSet.C
MC/CustomGenerators/PWGDQ/Hijing_Jpsiee002.C
MC/GeneratorConfig.C

The commit includes:
1) custom generator macro for PbPb 2018 (Hijing_Jpsiee002.C ) with centrality dependent injection (thanks to Ionut for the suggestion)
2) GenJPsiParaSet.C to set up user pT / y parametrizations (thanks to Markus for providing pT shapes from PbPb 2015)
3) small change in GeneratorConfig.C in order to use the functions at point 2)

update macros for PbPb 2018 MC simulations

---

QA/main_QAtrain_duo.C

Do to issues with the centrality selection the AliEventSelection
cannot be used in automatic mode in the QA train. Therefore the
fallback to the builtin event selection is used on the QA train.

Fallback to builtin event selection

---

QA/main_QAtrain_duo.C

C++-iterator-style syntax of TIter was not ignoring
null entries in TObjArray under ROOT5, leading to
a segfault due to access of nullptr.

[WIP] Use old-style TIter syntax

---

MC/ExtractEmbedded.C
MC/dpgsim.sh

Hi @miweberSMI @chiarazampolli 
This PR merges the gen.headers of the BG event to that of the embedded one, rewriting the TE tree in the galice.root (written to galice_EMB.root) of the latter when RemoveBKGFromGalice is called.
Note, now the RemoveBKGFromGalice is called automatically from the ExtractEmbedded() with {{keepMixed==false}}.
The steering script will need to save  galice_EMB.root as galice.root, as it is done for AliESDs.

Merge gen.headers in RemoveBKGFromGalice

---

MC/ExtractEmbedded.C

@miweberSMI This will flag the headers of bg. event by "particles_suppressed" in the title, still keeping the NProduced untouched. Such headers will not be processed in the AliMCEvent::AssignGeneratorIndex, but this will require https://github.com/alisw/AliRoot/pull/992
(from compilation point of view these two PRs are independent).

Flag gen headers with suppressed particles

---

MC/CustomGenerators/PWGHF/Pythia6_Perugia2011_D2Hdedicated.C

Fixes bug in Ds/Lc dedicated macro with multiplicity triggers (previous version used wrong variable in check on trigger option)

Fix multiplicity option selection on Ds/Lc dedicated macro

---

AOD/main_AODtrainRawAndMC.C

It will add to PileupVertexTracks pile-up vertices with >15 contributors.
Also the primary vertex found by the multiverterxed will be added (apart from the reconstruction
time primary vertex) tagges as a pile-up but with GetID()==-1

In PbPb filtering MVertexer will be rerun

---

MC/CustomGenerators/PWGDQ/Pythia6_Perugia2011_JpsiBJet13TeV.C

For J/psi in jets analysis, we proposed to generate non-prompt J/psi from B-hadron decay by pythia6.
* Create standalone macro to test the generator configuration.
Similar with HFjets, we can add b-bbar (as non-prompt) events by process kPyBeautyppMNRwmi. Then forced it decay (kBJpsiDiElectron) into J/psi with cuts on child (pT and Y). Obviously, StackFillOpt should be removed for both cases to keep the entire event. However, pT hard bin will be applied to enhance high pT jets samples.
The macro is from @miweberSMI.

[ALIROOT-8339] Non-prompt J/psi produced in B-hadron jets

---

AOD/main_AODtrainRawAndMC.C

Since the parameters are automatically determined from the ESDs,
it is better to not have them here - some we cannot get at this
point (e.g. B field), so better to not call them, even with
the default value, for simplicity.

Removing unneeded arguments from FMD-related AddTasks

---

AOD/AODtrainRawAndMC.C
AOD/main_AODtrainRawAndMC.C

Dear @catalinristea , @fprino , 
This is the change to have the V0 redone at filtering time, which we discussed to have as default. Can you check that everything is fine?
Pinging also @ddobrigk and @shahor02 , for information. 
@ddobrigk , the settings are those that you mentioned in https://alice.its.cern.ch/jira/browse/ALIROOT-8272?focusedCommentId=235244&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-235244
Chiara

Redo V0s before the gamma conversion task in AOD filtering

---

MC/dpgsim.sh

The new option --nocleanup for dpgsim.sh disables the cleaning up of
*.RecPoints.root *.Hits.root *.Digits.root *.SDigits.root files. The
default behaviour of the script without this option is unchanged. This
allows to study e.g. TRD digits of simulated events.

Add dpgsim.sh option to disable cleanup

---

DataProc/TPCSPCalibration/procResidData.C

If distNBinsY or distNBinsZ env.vars are equal to "fineY2X" or "fineZ2X" respectively, then for the corresponding dimension the fine binning hardcoded in y2x or z2x arrays will be used.
These options can be activated by setting in the ``spacePointCalibrationDefineTimeBinsvDrift.jdl``
````
DISTNBINSY = "fineY2X";
DISTNBINSZ = "fineZ2X";
````
Note: processing with fine binning is better to be done with longer time intervals, for the 3-runs-test I used distTimeBin=2400 instead of  distTimeBin=1200 (used for LHC18q/r)

Optionally activate fine binning in Y/X and Z/X

---

DataProc/CPass0/runCPass0.sh

runCPass0.sh had in the end extra check for , attributing it to runCalibTrain while the value
was set by the checkResTree.C for legitimate reason (no events in the ESD) not considered to be critical

Fix: remove redundant error check

---

DataProc/MergeOutputs/mergeByComponent.C

In my local tests this fixes the memory overrun.

Disable AliTPCcalibTime merging by very tight cut on stat.

---

MC/CustomGenerators/PWGHF/Pythia8_Monash2013_D2Hdedicated.C
MC/CustomGenerators/PWGHF/Pythia8_Monash2013_HF001.C

- Pythia8_Monash2013_HF001.C: config for HF MC productions. For the moment only the option with forced hadronic decays is implemented. 
- Pythia8_Monash2013_D2Hdedicated.C: config for MC productions with Pythia8 with trigger particles for D2H specific channels for ML studies. For the moment only two options implemented (Ds and half Ds half D+).

Add config for HF and D2H MC productions with Pythia8

---

MC/CustomGenerators/PWGDQ/GenJPsiParaSet.C
MC/CustomGenerators/PWGDQ/Hijing_Jpsiee002.C

Changes include: 
- update of prompt jpsi pt-spectra (from Pb-Pb 2018 data)
- EvtGen usage for B->J/psi+X decays

update generation macros for MC Pb-Pb 2018 (pass2)

---

MC/CustomGenerators/PWGDQ/Muon_GenParam.C
MC/CustomGenerators/PWGDQ/Muon_GenParamCharmonia_pp13TeV_1.C

The added macro "**Muon_GenParamCharmonia_pp13TeV_1.C**" creates a cocktail of generated J/psi (2/3 weight) and Psi(2s) (1/3 weight) particles in pp collisions at 13 TeV. The pt and rapidity input shapes were obtained via an iterative procedure in the analysis https://alice-notes.web.cern.ch/node/497.    
The structure of the macro is similar to "**Muon_GenParamUpsilon_pPb8TeV_1.C"**.
In addition, the macro "**Muon_GenParam.C** " is updated to have a _Charmonia_pp13TeV_1_ option.

Adding a custom generator for dimuon from j/psi and psi(2s)

---

AOD/main_AODtrainRawAndMC.C

These protections are needed to avoid crashes when we run productions with recent AliDPG and old AliPhysics.

Add protections for methods of AliAnalysisTaskWeakDecayVertexer

---

MC/CustomGenerators/PWGHF/Hijing_Pythia8_Monash2013_HF001.C

- Add config for D2H PbPb MC productions with hijing + pythia8 @cterrevo @jezwilkinson 
- @fprino @chiarazampolli I tested it and it seems to work (I simulated ~10 events since it is very slow, similarly to the one with pythia6), but I would like to ask you to check, in particular for the embedding and Lc options which I basically copied from [CustomGenerators/PWGHF/Hijing_HF001](https://github.com/alisw/AliDPG/blob/master/MC/CustomGenerators/PWGHF/Hijing_HF001.C). 
For the Lc in particular there are three options (two for the Lc to V0bachelor, one with pK0s only), that I implemented, by defining the trigger particle
https://github.com/fgrosa/AliDPG/blob/5df0e30f6dccd54c402f8fd3d6f183c46c735435/MC/CustomGenerators/PWGHF/Hijing_Pythia8_Monash2013_HF001.C#L44
and modifying the decays to be …

Add config for D2H PbPb MC with HIJING + Pythia8

---

MC/CustomGenerators/PWGDQ/Hijing_Jpsiee002.C

Custom generator macro changed in order to consider a centrality dependent injection based on bmin / bmax (needed for https://alice.its.cern.ch/jira/browse/ALIROOT-8511).

update centrality dep. injection based on bmin / bmax

---

MC/CustomGenerators/PWGLF/Hijing_Rsn005_moreLambda1520.C

This PR adds a new LF custom configuration `Hijing_Rsn005_moreLambda1520`.
The configuration is for the production discussed in 
https://alice.its.cern.ch/jira/browse/ALIROOT-8525
It is an extension of the `Hijing_Rsn005` setup, with `Lambda(1520)` injections happening in 2/11 slots instead of the original 1/10.

Hijing_Rsn005 version with more Lambda(1520)

---

MC/CustomGenerators/DPG/Dpmjet_Pileup.C
MC/CustomGenerators/DPG/EPOS_Pileup.C
MC/CustomGenerators/DPG/Hijing_Pileup_Cent.C
MC/CustomGenerators/PWGLF/Hijing_Nuclex004_pileup.C

Otherwise the wrong time is associated to the particles,
in case we use AliRoot that do not include
https://github.com/alisw/AliRoot/pull/1189
Also for EPOS and DPMJET and PWGLF:Hijing_Nuclex004_PileUp
See ALIROOT-8502

Swapping order in which we add trigger and pileup event.

---

MC/CustomGenerators/PWGHF/Hijing_Pythia8_Monash2013_HF001.C

Enlarge maximum lifetime limit from 1.e-15 to 0.7 to keep HF hadrons, which otherwise are removed from the kine tree with kPyCharm and kPyBeauty.

Add maximum lifetime (previously default 1.e-15)

---

MC/CustomGenerators/PWGHF/Pythia8_Monash2013_D2Hdedicated.C

This modification depends on this PR on AliRoot: https://github.com/alisw/AliRoot/pull/1213. There is however a protection to avoid crashes due to the usage of AliRoot tags without the option for the Xic0 semileptonic decay.

Add option for Xic0 semileptonic decay

---

MC/CustomGenerators/PWGLF/Box_Nuclex003.C

Hi @akalweit ,
I think in  PR #411 you forgot to return the cocktail generator as It is done for Box_Nuclex001 and Box_Nuclex002. I spotted this issue while simulating the anti-He3 passing in the detector and using your useful box (the simulation crashed) . Am I correct or am I missing something?

Return cocktail generator

---

MC/OCDBRun3.C

Observed as warning while testing Run3 simulation

fix OCDB macro if statement

---

AOD/main_AODtrainRawAndMC.C

This modification in main_AODtrainRawAndMC.C allows to set automaticallythe configuration for the vertexingHF filtering in the MC simulations anchored to 2018 Pb-Pb sample.
Some notes:
- the limits on the impact parameter, which are used to "decide" which of the configuration files should be used, are set based on the ones used in LHC20g2a and LHC20g2b productions. If in the future we are going to do a production in e.g. 10-20% or 20-30% centralities we may need to come back to them.
- to define automatically the configuration file based on the centrality interval of the MC production, I used the variables CONFIG_BMIN and CONFIG_BMAX, which are defined in the simulation script (dpgsim.sh). This means that this strategy would work for the AOD creation which runs in the reconstruction job. …

Special configs for HF productions in Pb-Pb

---

AOD/main_AODtrainRawAndMC.C

Ciao Chiara and Francesco,
For upcoming pass2 of 18l we'll need this update to set the proper FB for the AODs..
Please have a look then we need new tag before starting pass2.
Thanks!
Yours,
Catalin.

Updated AOD macro FB for upcoming pass2 LHC18*

---

AOD/main_AODtrainRawAndMC.C
MC/CustomGenerators/PWGHF/Hijing_pPb_Pythia8_Monash2013_D2Hdedicated.C
MC/CustomGenerators/PWGHF/Pythia8_Monash2013_D2Hdedicated.C

Adds new option, "LcToLpiDedicated", to the D2H custom generators for PYTHIA8 (pp) and HIJING+PYTHIA8 (p-Pb) in CustomGenerators.
Handling with new AliDecayer::kLcLpi option has dependency on AliRoot commit https://github.com/alisw/AliRoot/pull/1337 .

Adds handling of Lc->Lpi forced decays in D2H generators

---

MC/DetectorConfig.C

This feature is needed for the production of secondary nuclei discussed in ALIROOT-8651.

Add configuration with only central barrel tracking and PID detectors

---

MC/GeneratorConfig.C

Adds configuration for ptHard exponent weighting for:
Pythia8Jets, Pythia8JetsGammaTrg, and Pythia8GammaJet

Adds configuration for ptHard exponent weighting for PythiaJets

---

MC/CustomGenerators/PWGLF/ReadKine.C
MC/CustomGenerators/PWGLF/ReadKineAndHitsHe3.C
MC/Digitize.C
MC/Generate.C
MC/dpgsim.sh

These are the commits needed to run the production of ALIROOT-8651 with the selection of events after the trigger.
The strategy is to generate one event, run the transport, and run a macro to read the Kinematics (and the Hits) to check for specific particles and decide whether to go on with the digitisation.
Description of the code updates: I added an argument to dpgsim.sh to enable the "mode" with generation->selection-> digitization. It can be enabled with:
--selectevents SelMacro.C
where SelMacro.C is the name of the macro that will be used to select the events.
Note that the approach with --selectevents works properly only when we generate more than 1 event per job.
Still to be added to run the actual production:
- the final version of the macro to select the signals
- possibly a new …

Bunch of files for LF production with trigger on nuclei after trasport

---

MC/Config_LoadLibraries.C
MC/CustomGenerators/Upgrade/FOCAL_Generators.C
MC/DetectorConfig.C
MC/dpgsim.sh
MC/sim.C

Files touched:
1 MC/dpgsim.sh
1.1 Support for the "--detector FOCAL" option, which enables a special list of detector (see DetConfig.C)
1.2 Added the option "--focalGeometryFile " to be able to switch easily between different geometries
1.3 Only the "sim" mode is available for FOCAL simulations with these changes. No FOCAL digitization yet!!
2 MC/Config_LoadLibraries.C
Load the FOCAL libraries from the FOCAL external package if "--detector FOCAL" option is present
3 MC/DetectorConfig.C
3.1 Implemented an EDetector_t option for FOCAL and enabled/disabled needed detectors.
3.2 In DetectorInit(), run the AliPIPEFOCAL and FOCAL constructors for FOCAL simulations
4 MC/sim.C
Switch off LoadAlignFromCDB() and UseDetectorsFromGRP() for the FOCAL case, since there is no FOCAL alignment entry in …

Enable FOCAL simulations with alidpg

---

MC/CustomGenerators/PWGLF/Box_Nuclex_001_Extended.C

Custom generator for (anti)nuclei absorption studies. Added hypertriton to calculate its hadronic interaction length.

Extended Box_Nuclex_001, added hypertriton, pt_max=10 GeV, npart=10

---

.gitignore
MC/CustomGenerators/PWGGA/Pythia8Weighted_GammaTriggerAndJet.C

Test productions for pp 13 TeV show that the weight power
6 is too high and biases the spectrum too much towards high
pt, reducing the statistics at low pt. As the goal of a weighted
production is to have the spectrum as flat in pt-hard as possible
the weight needs to be reduced. Setting weight power to 4
based on PYTHIA8 tutorial main08.cc.

[ALIROOT-8678] Set weight power to 4

---

MC/GeneratorConfig.C

This PR adds new production modes for the latest version of STARLIGHT and depends on https://github.com/alisw/AliRoot/pull/1402.

updates for STARLIGHT r313

---

MC/CustomGenerators/Upgrade/FOCAL_Generators.C
MC/DetectorConfig.C
MC/DetectorInitFOCAL.C
MC/dpgsim.sh
MC/sim.C

1) Upgrade/FOCAL_Generators.C includes a new generator (boxWithDecay) which is a box generator for particles which require to be decayed (e.g. Z0, quarkonia). Also, there were many updates such that the generators capture the command line options and set the various kinematic options.
2) In the DetectorInitFOCAL.C we replaced FITv8 with FITv9
3) Added a new detector config "FOCALnoFIT", where we run the statndard detectors for FOCAL simulations, with the exception of FIT.
4) A few additional options were added in dpgsim.sh for eta ranges and full momentum

Few changes, needed for FOCAL simulations

---

.github/workflows/release.yml

Hardcoding ubuntu-18.04 will fail in future, as that version is deprecated by GitHub.
I also suspect it's the cause of the recent failures of this workflow, as no runners are available with this version.

Run release workflow on ubuntu-latest

---

MC/Geant4Config.C

The current Geant4 simulation is running in MT (multi-threading) mode while it should be run in sequential mode.
Ref1: https://github.com/alisw/geant4_vmc/blob/master/source/run/include/TG4RunConfiguration.h#L80
Ref2: https://github.com/alisw/AliRoot/blob/master/test/vmctest/ppbench/g4Config.C#L42

Set Geant4 sequential mode by default

---

MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn_f0f1.C

Force decay mode of injected resonance and add two more resonances

Force decay mode

---

MC/CustomGenerators/PWGHF/Pythia8_Monash2013_HFDsreso.C

This PR contains an update of the Ds resonance dedicated MC Custom Generator: unecessary multiplicity threshold is removed.
It requires the PR: https://github.com/alisw/AliRoot/pull/1475 (MERGED)

Removing multiplicity threshold from HFDreso custom generator

---

MC/CustomGenerators/PWGGA/Hijing_Gamma002.C

reduce number of signals for the 30-50% centrality case to aim for 30 charged tracks with pt>0.15 GeV within the TPC acceptance.

Reduce number injected signals in Hijing_Gamma002.C

---

MC/CustomGenerators/PWGLF/Hijing_Sexaquark.C

Call of SetPhiRange now uses the correct units (degrees, instead of radians)

Bugfix HIJING + anti-sexaquark + anti-neutrons gen.
