alisw/AliDPG

- README.md
This is my modest attempt at documenting the tagging nomenclature we discussed.
> Attempt to describe the tagging procedure

- MC/CustomGenerators/PWGLF/Hijing_Nuclex005.C
- MC/GeneratorConfig.C
Added generator with the injection of Ps(2100), Ps(2500), d*(2380) + CC
> Add generator Hijing_Nuclex005

- MC/CustomGenerators/PWGLF/Epos_Nuclex005.C
- MC/GeneratorConfig.C
Please notice that it requires AliRoot from v5-09-02
> New PWGLF generator Epos_Nuclex005

- MC/CustomGenerators/PWGLF/Epos_Nuclex001.C
Hi @preghenella ,
this is the custom generator with the configuration requested by the NUCLEX pag MC.
Cheers!
Max
> EPOS generator with injected (anti-)(hyper-)nuclei

- MC/CustomGenerators/PWGLF/Hijing_Rsn001.C
The configuration needed for ALIROOT-7189 is created and has been tested.
> Added PWGLF/Hijing_Rsn001.C configuration

- MC/CustomGenerators/PWGLF/EPOS_StrInj_pPb8.C
Rapidity ranges for flat production have been changed in order to comply with the p-Pb system
> Change the rapidity ranges in EPOS_StrInj_pPb8.C

- MC/CustomGenerators/PWGMM/Phojet_DiffTune.C
> Added PWGMM/Phojet_DiffTune configuration

- MC/CustomGenerators/PWGLF/DPMJET_OmegaTrg_pPb8.C
- MC/CustomGenerators/PWGLF/DPMJET_XiTrg_pPb8.C
- MC/CustomGenerators/PWGMM/Phojet_DiffTune.C
> Custom generators based on DPMJET with triggered cascades

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Nuclex001.C
- MC/GeneratorConfig.C
Hi @preghenella,
these are the changes and the custom generator required by [ALIROOT-7306](https://alice.its.cern.ch/jira/browse/ALIROOT-7306).
I already tested but please have a look and tell me if you find something pathological.
Thanks a lot!
Cheers,
Max
> Nuclei generator for pp collisions

- MC/GeneratorConfig.C
Dear Roberto,
here are the changes we discussed, can you have a look and approve if OK with you?
Thanks,
Michael
> GammaJet and GammaTriggeredJet configurations for PYTHIA8

- MC/CustomGenerators/PWGUD/Dime.C
This commit is related to this production request ALIROOT-7398
> Added custom DIME generator

- MC/CustomGenerators/PWGUD/Starlight_flat_rho.C
> Custom generator for pipi flat up to 4 GeV/c^2

- MC/CustomGenerators/PWGLF/Hijing_Str003.C
As discussed here: 
https://alice.its.cern.ch/jira/browse/ALIROOT-7407
> Addition of one more mat. bud. testing file

- MC/DetectorConfig.C
Dear all, this is the fix for the TRD geometry in the simulation. Best regards, Raphaelle
> Fix for the TRD geometry in the simulation

- MC/CustomGenerators/PWGLF/Hijing_Rsn003.C
- ALIROOT-7529
- provided by ajay.kumar.dash@cern.ch
> New custom macro for PWG-LF production with injected resonances

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_RsnNcl001.C
Hi @miweberSMI ,
this configuration will be needed for an upcoming production request by PWGLF.
We still need to put some new states that are not present in the current AliRoot release, thus expect an update on this!
Thanks and cheers!
Max
> Resonance + Nuclei injection scheme

- MC/CustomGenerators/PWGLF/DPMJET_RsnInject_pPb8TeV.C
- DPMJET + injected resonances for p-Pb 8 TeV
- Author: rama.chandra.baral@cern.ch
> New PWG-LF custom generator

- MC/CustomGenerators/PWGLF/DPMJET_RsnInject_pPb5TeV.C
> DPMJET f0 and f2 injected pPb5TeV

- MC/CustomGenerators/PWGHF/Hijing_HF001.C
This is a fix for a further line that was forgotten when moving this piece of code to CustomGenerators.
> Adding creation of AliGenCocktail

- MC/CustomGenerators/PWGHF/Pythia6_Perugia2011_HF001_HighMult.C
CustomGenerator for the analysis of high-multiplicity pp events from PYTHIA.
> D2H pp production with high mult cut

- MC/CustomGenerators/PWGLF/Hijing_XeXe_Nuclei.C
Ciao Michael,
this new generator will be necessary for an upcoming production request.
Cheers!
Max
> Adding a new generator for nuclei in Xe-Xe

- MC/CustomGenerators/PWGLF/Hijing_Rsn003.C
- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn002.C
Hi @miweberSMI ,
with this PR we introduce the generators for the resonances productions. I ask @akalweit to have a look if it is fine with him.
Cheers,
Max
> Resonance generators

- MC/CustomGenerators/PWGLF/Dpmjet_Rsn_pPb001.C
- MC/CustomGenerators/PWGLF/Hijing_Rsn003.C
- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn002.C
- MC/GeneratorConfig.C
Hi @miweberSMI , @aknospe,
could you please check that this PR does what is required by [this production](https://alice.its.cern.ch/jira/browse/ALIROOT-7609)?
Thanks a lot,
Cheers,
Max
> Move Resonance p-Pb generator to AliGenParam

- MC/Config.C
- MC/dpgsim.sh
- correction: removing "$" for setting CONFIG_TRIGGER in dpgsim.sh
- setting from outside should have priority: changing "else" into "elif" statement
- recognize Custom config file from ALIDPG directory: adding additional if statements in "Config.C"
> Small modifications for TOF in data taking

- MC/Config.C
- MC/Config_LoadLibraries.C
- MC/DetectorConfig.C
- MC/ExportGRPinfo.C
- MC/GeneratorConfig.C
- MC/ReconstructionConfig.C
- MC/SimulationConfig.C
- MC/rec.C
- MC/sim.C
This is only for testing and discussion right now, please do not merge yet
> Fixes for ROOT 6, disable some stuff which I could not make run easily

- DataProc/TPCSPCalibration/CreateCorrMapObj.C
- DataProc/TPCSPCalibration/procResidData.C
- MC/CheckESD.C
- MC/Config.C
- MC/CreateSnapshot.C
- MC/DetectorConfig.C
- MC/GeneratorConfig.C
- MC/OCDBConfig.C
- MC/ReconstructionConfig.C
- MC/SimulationConfig.C
- MC/dpgsim.sh
- MC/rec.C
- MC/sim.C
+ call OCDBConfigCustom with rec/sim flag
> Fixes for root5/root6 compatibility

- MC/CreateSnapshot.C
- MC/CustomGenerators/Upgrade/Hijing_QED.C
- MC/DetectorConfig.C
- MC/GeneratorConfig.C
- MC/OCDBRun3.C
- MC/ReconstructionConfig.C
- MC/SimulationConfig.C
- MC/dpgsim.sh
- probably not the nicest solution but closest to what Ruben proposed in custom macros
- additionally adding a first generator macro with HIJING + QED electrons
> Adapting Rubens custom macros for Run3 geometry simulations

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Nuclex001.C
Ciao @miweberSMI , @fprino ,
this (trivial) fix is required to recover two failing periods of ALIROOT-7649.
Let me know if you need further info!
Cheers,
Max
> Fix string size for the particle name

- MC/DetectorConfig.C
Fix needed for https://alice.its.cern.ch/jira/browse/ALIROOT-7743
> Fix: use AliPIPEupgrade for Run3

- DataProc/MergeOutputs/mergeByComponent.C
Complements #138 and only affects release validation processing
> Ensure local files contain remote name in merge

- MC/SimulationConfig.C
This is a fix for the problem https://alice.its.cern.ch/jira/browse/ALIROOT-7743?focusedCommentId=218262&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-218262
> In Run3 mode discard GRP written by AliSimulation

- MC/EXTRA/gen_ampt.sh
bump the AMPT version that AliDPG loads to the latest AMPT version available in AliGenerators
>  bump AMPT version to latest

- DataProc/MergeOutputs/merge.C
* Fix variable declared twice
* Fix ambiguous call to `StartAnalysis()`
> Fix merge.C errors in ROOT 6

- QA/QAtrainsim.C
> Remove extra Format argument

- DataProc/CPass0/main_makeOCDB.C
- DataProc/CPass0/runCPass0.sh
- DataProc/CPass1/main_makeOCDB.C
- DataProc/CPass1/runCPass1.sh
- DataProc/TPCSPCalibration/CreateCorrMapObj.C
- DataProc/TPCSPCalibration/createOCDBTPCSPDistCalib.sh
- DataProc/TPCSPCalibration/procVDTime.sh
@dberzano , @fprino , @shahor02, can you have a look at these changes? It is to take the MirrorSE from an env variable, for the OCDB uploads.
Chiara
> Taking list of MirrorSE from env variable

- AOD/AODtrainRawAndMC.C
- AOD/main_AODtrainRawAndMC.C
> Revert "Initial commit for unified main/re-filtering AOD macro"

- AOD/AODtrainRawAndMC.C
- AOD/main_AODtrainRawAndMC.C
Hi,
This would be the proper pull request. Thanks and sorry for the issues.
Yours,
Catalin.
> Proper initial commit for AOD refiltering macro

- MC/FlukaConfig.sh
- MC/dpgsim.sh
> Take coreFlukaVmc.inp from AliRoot

- Utils/compareTags.sh
There is also the script runCompareAllHistos.sh which was written to
be integrated in the RelVal, this is what I use.
> Script to compare two tags.

- AOD/main_AODtrainRawAndMC.C
Ciao @fprino , @chiarazampolli 
Here are some small updates to make AOD macro (re-filtering part) ROOT6 compliant.
Please have a look and merge these changes.
Thanks a lot!
Yours,
Catalin.
> Updates for ROOT6 (re-filtering macro)

- DataProc/CPass0/main_makeOCDB.C
- DataProc/CPass1/main_makeOCDB.C
Dear all,
here is the pull request to increase the limit for the number of TRD chambers from 130 to 140.
Best regards,
Raphaelle
> Increase limit for the TRD bad chambers from 130 to 140

- DataProc/CPass0/checkResTree.C
In case of corruption will write to stdout CORRUPTED Residuals file, ev ...
> macro to check the integrity of residual tree

- DataProc/CPass0/checkResTree.C
- DataProc/CPass0/runCPass0.sh
Hello @shahor02 ,
Can you check if these changes are fine with you?
Chiara
> Incorporating the check for the integrity of the ResTree in the script

- MC/CustomGenerators/PWGDQ/Muon_GenParam.C
- MC/CustomGenerators/PWGDQ/Muon_GenParamSingle_PbPb5TeV_1.C
Hi Michael,
I am preparing to run single muon MC anchored to the new PbPb data (for efficiency studies).
I will open the ticket once the misalignment file related to the new alignement will be produced.
Cheers,
Philippe
> new single muon parameterisation for PbPb at 5TeV

- MC/GeneratorConfig.C
- first event to be processed
- tracking neutrons or spectators only
> Adding more processing options for RELDIS:

- MC/CustomGenerators/PWGLF/Box_Nuclex001.C
Ciao @miweberSMI ,
this new generator has been requested by some analysers to check GEANT4 response for nuclei in the MC. I did few checks locally and it was working. We will ask a small production (we still remember that we owe you a QA for the embedding :) ) using this generator in the next days.
Thanks a lot,
Max
> Add new box generator for GEANT3/GEANT4 studies in LF

- MC/DetectorConfig.C
> Revert "auto-disable ADA PMT shielding if year<2017"

- MC/CustomGenerators/PWGDQ/Hijing_Jpsiee001.C
- MC/dpgsim.sh
also fix naming label for JPsi embedding
> Fix usage of debug option (remove shift)

- MC/CustomGenerators/PWGDQ/Hijing_LMee001.C
- MC/CustomGenerators/PWGDQ/Hijing_LMee002.C
- split into two macros: All (001) and HFonly (002)
- for 001 add option to produce light flavour cocktail only: opt.Contains(LF)
- for 002 add option to produce centrality dependent injection: opt.Contains(CentDepHF)
(exact numbers to be adapted)
- for both add embedding functionality: HIJING only if non-embedded configuration
> Update injected LMee configurations for Pb-Pb:

- DataProc/reshuffle/ReshuffleRawTree.C
- DataProc/reshuffle/aliroot_dpgReshuffle.sh
- DataProc/reshuffle/rec_pass98.jdl
- DataProc/reshuffle/runreshuffle.sh
Ciao @chiarazampolli , @fprino 
Here is the final EMCAL reshuffle configuration. 
It's just running in grid and jobs seem to do just fine with it.
Thanks!
Yours,
Catalin.
> Added EMCAL reshuffle configuration

- MC/Config.C
Some other commits went in - I don't know why, mysteries of git for me - but anyway they don't change anything (they are my previous commits).
>  Updating default value of ptHardMin for HIJING (ALIROOT-8211) 

- MC/CustomGenerators/PWGHF/Hijing_HF001.C
Fix array of labels in Hijing_HF001.C custom generator
> fix to label array in Hijing_HF001.C (HF custom generator)

- MC/CustomGenerators/PWGHF/Hijing_HFjetPbPb.C
Config for HF-jet productions in Pb-Pb. Hijing+Pythia6 (c/b enhancement with 10 Pythia per Hijing event).
> config for Hijing+Pythia HF-jet Pb-Pb productions

- AOD/main_AODtrainRawAndMC.C
Ciao @chiarazampolli , @fprino 
Here is the pull request to save the logs for re-filtering productions - please merge if you find it appropriate.
Thanks!
Yours,
Catalin.
> Updated AOD macro to keep logs, intended for central productions

- MC/ExtractEmbedded.C
- MC/ExtractEmbeddedWrapper.C
Filtered friend tree is stored by default in AliESDfriend_EMB.root
> friend info for extracted tracks is also filtered

- AOD/main_AODtrainRawAndMC.C
- DataProc/CPass1/runCPass1.sh
- DataProc/PPass/runPPass.sh
- QA/main_QAtrain_duo.C
This is the PR with the changes that @ekryshen and I implemented to make the automatic post-processing of the Phys Selection work. 
@fprino , @catalinristea , @germainma , can you have a look? Can you also add Elena, I don't know her guthub account. 
Once merged, we could do some tests as we discussed with the tarball. 
Chiara
> Changes to make the PhysSelection post-processing work in QA

- AOD/AODtrainRawAndMC.C
- AOD/main_AODtrainRawAndMC.C
- re-added AliAnalysisTaskMuonRefit
- use automatic loading of alignment storage to setup the task
> Re-add muon refit task

- MC/Config.C
- MC/Geant4Config.C
- MC/dpgsim.sh
There is again the same commit for ESDfriends of yesterday, I don't know why, but it should be harmless (not changing anything).
>  Adding new argument to define G4 Physics List

- MC/CustomGenerators/PWGHF/Pythia_pp_XiC.C
Config file for simulation of XiC to hadronic decays in pp collisions with Pythia 8.
> Add config file for XiC simulation

- MC/CustomGenerators/PWGDQ/Hijing_LMee001.C
- MC/CustomGenerators/PWGDQ/Hijing_LMee002.C
+ Adding optional selection of all decay daughters for AliGenParam
+ fix for ROOT6 (casting)
+ some minor printout cosmetics
> Adding optional selection of all decay daughters for AliGenParam 

- MC/CustomGenerators/PWGHF/Pythia6_Perugia2011_D2Hdedicated.C
proposed to be used by multiple productions for analyses aiming at QM: for dedicated productions of Lc and D_s, including sign of trigger particle and option for HMSPD/V0HM triggers
> Add new macro for Lc / D_s dedicated generation, including HM trigger options

- MC/CustomGenerators/PWGHF/Pythia6_Perugia2011_HF001_HighMult.C
SetTriggerChargedMultiplicity modified with minimum multiplicity thresthold set to 40, for HM SPD studies
> high mult trigger thesh modified for HMSPD

- MC/Geant4Config.C
Ciao @chiarazampolli and @fprino ,
This is the last update for Geant4Config by Ivana, with simplified volume option for BERT+biasing.
Thanks!
Yours,
Catalin.
> Updated option for BERT+biasing, from Ivana

- MC/CustomGenerators/PWGDQ/Pythia6_Perugia2011_JpsiBJet13TeV.C
Applied changes discussed in https://github.com/alisw/AliDPG/pull/310
> [ALIROOT-8339] Add J/psi pT cut and FIX decay type of EvtGen

- MC/SimulationConfig.C
- MC/dpgsim.sh
@chiarazampolli this PR adds to dpgsim.sh a switch to enable extra distortions due to the CV.
Please don't merge at the moment, to be discussed a the Thu. meeting.
> Switch to enable extra distortions

- MC/CustomGenerators/PWGHF/Pythia6_pp_XiC.C
Hello,
this is the update config for XiC simulation (remove omegaC and enlarge eta range of the trigger particle, https://alice.its.cern.ch/jira/browse/ALIROOT-8281)
Cheers
Grazia
> remove omegaC and enlarge eta range of the trigger particle

- MC/CustomGenerators/DPG/Hijing_Pileup.C
New generator to be used for simulations of Pb-Pb with pileup.
> Pileup generator for PbPb

- DataProc/PPass/main_rec.C
- MC/ReconstructionConfig.C
- MC/dpgsim.sh
This is to support the special PID for tracking for nuclei being introduced with alisw/AliRoot#1017
Needs to be tested before merging!
cc. @akalweit
> Support special nuclei reconstruction

- MC/ReconstructionConfig.C
- MC/dpgsim.sh
Ciao @chiarazampolli, @fprino, @shahor02 
Here is a CleanESD proposal for MC reconstruction, as discussed in ALIROOT-8418. Please have a look and let me know if I missed anything. Thanks!
Yours,
Catalin.
> CleanESD for MC reconstruction

- QA/main_QAtrain_duo.C
Ciao,
Since we're ready for a new tag, maybe we can take also this small fix, for data processing. 
If late, it can also wait for next time.
Thanks!
Yours,
Catalin.
> Small fix for QA merging

- MC/CustomGenerators/PWGDQ/Hijing_Jpsiee001.C
- MC/CustomGenerators/PWGDQ/Hijing_Jpsiee002.C
- MC/CustomGenerators/PWGDQ/Hijing_JpsieeXeXe.C
- MC/CustomGenerators/PWGDQ/Hijing_LMee001.C
- MC/CustomGenerators/PWGDQ/Hijing_LMee002.C
- MC/CustomGenerators/PWGDQ/Hijing_LMee003.C
- MC/CustomGenerators/PWGDQ/Hijing_Starlight.C
- MC/GeneratorConfig.C
All touched macros except starlight one work with these fixes on Root6. starlight needs something else I could not quickly figure out.
> Root6 fixes for PWGDQ

- DataProc/CPass1/main_recCPass1.C
- HI (PbPB/XeXE) --> 0.2
- pp --> 0.5
- pA/Ap --> 1.0
> Fraction of friends for CPass1 now depends on coll system.

- MC/CustomGenerators/DPG/Dpmjet_Pileup_Cent.C
- MC/CustomGenerators/DPG/EPOS_Pileup_Cent.C
- MC/CustomGenerators/DPG/Hijing_Pileup.C
- MC/CustomGenerators/DPG/PerformanceGenerator_Pileup.C
- Utils/GetTriggerBCMaskAndMu.C
first implementation of EPOS and DPMJET with pile-up 
EPOS and DPMJET macros not fully tested yet
> move method to retrieve trigger mask and mu from several macros to a single one

- MC/CustomGenerators/PWGDQ/Muon_LowMassCocktail.C
from Satoshi Yano, needed for ALIROOT-8401
> Adding low mass dimuon cocktail

- MC/Config.C
- MC/Geant4Config.C
Hello @gconesab , @fprino , @catalinristea , 
Can you check? This is what we discussed in JIRA (https://alice.its.cern.ch/jira/browse/ALIROOT-8401), to change the default G4 phys list and update for the EMCAL.
Adding also @ihrivnac , and @amorsch for information.
> Change default physics list for G4, and fix for EMCAL settings

- MC/CustomGenerators/DPG/EPOS_Pileup_Cent.C
- MC/GeneratorConfig.C
Please @fprino, @chiarazampolli , @catalinristea, let me know what you think, is this a proper solution or something more clever is needed.
> Create a second pool of events for pile-up simulation with EPOS

- MC/ExtractEmbedded.C
Copy all CaloClusters having at least 1 signal label, discarding those which contain BG labels only,
for the saved clusters the BG labels will be set to -1 but not removed.
Matched eliminated tracks are removed from the cluster track list.
All cells (also having BG labels only) contributing to saved clusters will be preserved
> Extract Calo data

- MC/GeneratorConfig.C
Request from Uliana Dmitrieva and Yuri Kharlov ALIROOT-8473
> Fix ptmin/max and ymin/max external setting for QED generator ALIROOT-8473

- MC/CustomGenerators/DPG/EPOS_Pileup_bkg.C
- MC/GeneratorConfig.C
Removing also "&" when generating EPOS event in fifo
> [ALIROOT-8487] EPOS pileup generator for bkg in embedding MCs

- MC/CustomGenerators/PWGLF/Box_Nuclex003.C
Adding additional box generator needed for ALIROOT-8542
> Adding additional generator for ALIROOT-8542

- AOD/main_AODtrainRawAndMC.C
Ciao, 
Small change related to ROOT6. I'll merge it right away. Thanks!
Yours,
Catalin.
> Fix declaration and warning for ROOT6

- MC/CustomGenerators/PWGHF/Hijing_Pythia8_Monash2013_D2Hdedicated.C
adding Hijing using Pythia8_Monash2013_D2Hdedicated.C for Xic0 semileptonic in pPb
> add Hijing Xic0Semileptonic

- MC/CustomGenerators/PWGHF/Pythia8_Monash2013_D2Hdedicated.C
Add Omegac0 -> Omega^- pi^+ in Pythia8_Monash2013_D2Hdedicated.C
> Add Omegac0 -> Omega^- pi^+ in Pythia8_Monash2013_D2Hdedicated.C

- MC/CustomGenerators/PWGHF/Pythia8_Monash2013_HF001_HighMult.C
Pythia8 High mult Config with threshold to be set in the command
> Pythia8 High mult Config

- MC/CustomGenerators/PWGLF/Hijing_pPb_HyperTriton.C
- MC/CustomGenerators/PWGLF/Hijing_pPb_Nuclex001.C
This is the fix needed for ALIROOT-8517, as reported by Catalin in the Jira ticket
> Add missing line to retrieve environment variable

- MC/CustomGenerators/PWGHF/HF_Muon_GenParam.C
- MC/CustomGenerators/PWGHF/HF_Muon_GenParamSingle_Pbp_CMSH_16s.C
- MC/CustomGenerators/PWGHF/HF_Muon_GenParamSingle_Pbp_CMSL_16s.C
- MC/CustomGenerators/PWGHF/HF_Muon_GenParamSingle_pPb_CMSH_16r.C
- MC/CustomGenerators/PWGHF/HF_Muon_GenParamSingle_pPb_CMSL_16r.C
From Sibaliso Mhlanga.
To generate the different configurations one should specify to dpgsigm.sh
--generator PWGHF:HF_Muon_GenParam:HF_single_pPbcmsl16r
--generator PWGHF:HF_Muon_GenParam:HF_single_Pbpcmsl16s
--generator PWGHF:HF_Muon_GenParam:HF_single_pPbcmsh16r
--generator PWGHF:HF_Muon_GenParam:HF_single_Pbpcmsh16s
> Macros for MC configuration of FONLL simulations ALIROOT-8647

- MC/CustomGenerators/PWGGA/Pythia8Weighted_GammaTriggerAndJet.C
- MC/GeneratorConfig.C
to avoid backward incompatibility
> Move setting of weight from GeneratorConfig.C to CustomGenerator macro

- MC/CustomGenerators/PWGLF/Hijing_AbsStudies.C
This new generator will be needed for an upcoming MC request.
@mcolocci please check the pt ranges of the generators
> Add generator for absorption studies

- MC/CustomGenerators/PWGHF/Pythia8_Monash2013_D2Hdedicated.C
New MC option for Omegac0 -> Omega +e +nu
> Add option for Omegac0 semi-leptonic channel

- MC/CustomGenerators/PWGLF/Box_Nuclex_001_Extended.C
Injecting 20 nuclei per species. Restricted rapidity interval for embedded nuclei (0.8 -> 0.5)
> updated injection scheme

- MC/CustomGenerators/PWGHF/Pythia8_Monash2013_ThetaC.C
This config works only with https://github.com/alisw/AliRoot/pull/1393
> Add custom config for ThetaC pentaquark

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn004.C
Create a generator to inject multiple strange pentaquark states into 13 TeV pp collisions to study efficiency
> Create Pythia8_Monash2013_Rsn004.C for Ps analysis

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn005.C
Requested by Enrico Fragiacomo for pp 5 TeV Sigma1385 analysis
> New RSN generator for rho/sigma1385 analysis

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn_f2f0.C
- Add custom generator for requesting
> Add f0f2 injector

- MC/CustomGenerators/PWGHF/Pythia8_Monash2013_D2Hdedicated.C
Add the 4body decay mode for the Xic0 semileptonic simulation
> MC option for Xic0 semileptonic mode

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn_f0f1.C
4 Resonances:
f1(1285) 20223
f1(1420) 20333
f0(1710) 10331
f0(1500) 90302
Will be used for the new approval.
> Add custom generator for f0 f1 resonances

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn_f0f1.C
> fix the nParticle

- MC/CustomGenerators/PWGDQ/Pythia8_Monash_HighMassDimuon.C
Generator Custom using PYTHIA8 Monash Tune for high mass dimuon analysis
> PWGDQ: Adding generator custom for high mass dimuon

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn_f0f1.C
> Fix typo on the PDG code

- MC/CustomGenerators/PWGHF/Pythia8_Monash2013_HFDsreso.C
This PR contains the possibility to set the multiplicity interval in the Ds-resonance custom generator.
It requires the PR: https://github.com/alisw/AliRoot/pull/1475
> Add multiplicity threshold in Ds reso custom generator

- MC/CustomDecayTables/BTOPSIJPSITODIELECTRON.DEC
- MC/CustomGenerators/PWGDQ/GenJPsiParaSet.C
- MC/CustomGenerators/PWGDQ/Pythia6_Perugia2011_JpsiPsi2ee13TeV.C
- MC/GeneratorConfig.C
needed for the psi2s+jpsi (->ee) production requested at the PB on May 11th (https://alice.its.cern.ch/jira/browse/ALIROOT-8843)
> include psi2s -> ee

- MC/CustomGenerators/Upgrade/FOCAL_Generators.C
I added the pythia8jetjet MC generator for the FOCAL simulation.
> Adding pythia8jetjet MC for FOCAL simulation

- MC/CustomGenerators/PWGHF/Hijing_pPb_Pythia8_Monash2013_D2Hdedicated.C
HIJING XicSemilepDedicated option: added Xic+
> HIJING_XicSemilepDedicated

- MC/DetectorInitFOCAL.C
Changing the diameter of the beam pipe going from after the flange to after FOCAL to 3cm.
> Change beam pipe radius inside FOCAL

- MC/CustomGenerators/PWGLF/Pythia8_Monash2013_Rsn_f0f1.C
Force decay, this has to be used together with https://github.com/alisw/AliRoot/pull/1484
> Use decayer for all decay particles

- MC/CustomGenerators/PWGGA/Pythia8JJ_EtaPrime.C
- MC/GeneratorConfig.C
I added eta'-biased generator based on JJ MC. @gconesab, could you review the changes?
> add eta' biased JJ MC generator

- MC/CustomGenerators/PWGHF/Pythia8_Monash2013_HFDsreso.C
This PR includes updates to the forced decay channels for the Ds-resonance custom generator.
It requires the PR: https://github.com/alisw/AliRoot/pull/1493.
> Updating forced decay in Ds-resoncances custom generator

- MC/DetectorInitFOCAL.C
Slightly changing the position of the flange and the end of the conical beam pipe.
> Changing the position of the flange and the cone

- MC/CustomGenerators/PWGLF/Hijing_Sexaquark.C
- generator to interface https://github.com/alisw/AliRoot/pull/1504 with the [AliDPG](https://github.com/alisw/AliDPG) scripts
> Added HIJING + anti-sexaquark + anti-neutrons gen.
